const NEW_GAME = 'NEW_GAME';
const PROGRESS_TURN = 'PROGRESS_TURN';
const SET_ACTION = 'SET_ACTION';
const MAKE_DECISION = 'MAKE_DECISION';
const SET_SHOW_LOCATION_LIST = 'SET_SHOW_LOCATION_LIST';
const SET_SHOW_PERSON_LIST = 'SET_SHOW_PERSON_LIST';
const SET_SELECTED_LOCATION = 'SET_SELECTED_LOCATION';
const SET_SELECTED_PERSON = 'SET_SELECTED_PERSON';
const GET_SELECTED_PERSON_LOG = 'GET_SELECTED_PERSON_LOG';

export {
  NEW_GAME,
  PROGRESS_TURN,
  SET_ACTION,
  MAKE_DECISION,
  SET_SHOW_LOCATION_LIST,
  SET_SHOW_PERSON_LIST,
  SET_SELECTED_LOCATION,
  SET_SELECTED_PERSON,
  GET_SELECTED_PERSON_LOG,
};
